#!/bin/sh
while read file
do
        case "$1" in
        "d")
                mv "$file" ~/.trash ;;
        "r")
                convert -rotate 90 "$file" "$file" ;;
        "c")
                echo -n "$file" | xclip -selection clipboard ;;
        "w")
                xwallpaper --zoom "$file" && cp "$file" ~/.local/wallpaper.png ;;
        esac
done
