#!/bin/bash

intern="LVDS1"
extern="HDMI1"

case "$1" in
	"disconect") xrandr --output "$extern" --off --output "$intern" --auto ;;
	"duplicate") xrandr --output "$extern" --set audio force-dvi --mode 1920x1080 && xrandr --output "$intern" --auto --output "$extern" --same-as "$intern" ;;
	"extend") xrandr --output "$extern" --set audio force-dvi --mode 1920x1080 && xrandr --output "$intern" --auto --output "$extern" --right-of "$intern" ;;  
	*) notify-send "Unknow operation!" ;;
esac

