#!/bin/sh
while read file
do
        case "$1" in
        "p")
		wal -i "$file" && killall dunst && 
		notify-send "Do you liked your new pywal generated scheme?";;
	"b")
		feh --bg-fill "$file" ;;
        "y")
		echo -n "$file" | tr -d '\n' | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	esac
done
